#!/usr/bin/env bash
# domain-architect — pre-push doc-drift hook.
#
# Once per push: find changed files that live in a DOCUMENTED area (a dir with
# ARCHITECTURE.md / CLAUDE.md / DATA_FLOW.md, or a path an ADR's `governs:`
# lists). Then either auto-refresh the governing docs (rewrite mode) or just
# flag them (flag mode).
#
# Config (env or git config):
#   DOMAIN_ARCHITECT_MODE = rewrite | flag      (default: flag — safe)
#   DOMAIN_ARCHITECT_CLAUDE = claude            (the Claude CLI binary)
#
# Rewrite mode requires the Claude CLI. It edits ONLY stale sections (grounded in
# the diff), commits the result as its own visible commit, and ABORTS the push so
# that doc commit is included — review with `git show`, then push again.
set -euo pipefail

MODE="${DOMAIN_ARCHITECT_MODE:-$(git config --get domainArchitect.mode || echo flag)}"
CLAUDE_BIN="${DOMAIN_ARCHITECT_CLAUDE:-claude}"
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(git rev-parse --show-toplevel)"

# Range being pushed: compare against the upstream/main merge-base.
BASE="$(git merge-base HEAD "@{upstream}" 2>/dev/null || git merge-base HEAD origin/main 2>/dev/null || echo "")"
[ -z "$BASE" ] && exit 0
CHANGED="$(git diff --name-only "$BASE"..HEAD -- "$ROOT" | sed "s#^#$ROOT/#")"
[ -z "$CHANGED" ] && exit 0

# Only CODE changes signal drift — editing a doc isn't itself stale-making (and a
# PR that adds/updates docs shouldn't flag the very docs it touches). Drop the doc
# files (ARCHITECTURE/CLAUDE/DATA_FLOW.md and anything under docs/) from the triggers.
CHANGED="$(printf '%s\n' "$CHANGED" | grep -vE '/(ARCHITECTURE|CLAUDE|DATA_FLOW)\.md$|/docs/' || true)"
[ -z "$CHANGED" ] && exit 0

# A file is "documented" if an ancestor dir holds a doc, or an ADR governs it.
doc_for() {  # echo the governing doc(s) for a changed file, or nothing
  local f="$1" d; d="$(dirname "$f")"
  while [ "$d" != "$ROOT" ] && [ "$d" != "/" ]; do
    for name in ARCHITECTURE.md CLAUDE.md DATA_FLOW.md; do
      [ -f "$d/$name" ] && echo "$d/$name"
    done
    d="$(dirname "$d")"
  done
  # ADRs whose `governs:` frontmatter matches this path. Process substitution +
  # `|| true` so a no-match grep (no ADR has `governs:` yet) can't fail the
  # function under `set -e -o pipefail` and silently abort drift detection.
  while IFS= read -r adr; do
    [ -n "$adr" ] || continue
    while IFS= read -r p; do
      [ -n "$p" ] && [[ "$f" == *"$p"* ]] && echo "$adr"
    done < <(awk '/^governs:/{flag=1;next}/^[a-z]+:/{flag=0}flag&&/-/{gsub(/[- ]/,"");print}' "$adr" 2>/dev/null || true)
  done < <(grep -rliE "governs:" "$ROOT/docs/adrs" 2>/dev/null || true)
  return 0
}

DOCS="$(while IFS= read -r f; do doc_for "$f"; done <<< "$CHANGED" | sort -u)"
[ -z "$DOCS" ] && exit 0

echo "[domain-architect] changed files touch documented areas. Governing docs:"
echo "$DOCS" | sed "s#^$ROOT/#  - #"

if [ "$MODE" != "rewrite" ]; then
  echo "[domain-architect] flag mode — review the docs above (set DOMAIN_ARCHITECT_MODE=rewrite to auto-refresh)."
  exit 0
fi

if ! command -v "$CLAUDE_BIN" >/dev/null 2>&1; then
  echo "[domain-architect] rewrite mode but '$CLAUDE_BIN' not found — falling back to flag. Install the Claude CLI or set DOMAIN_ARCHITECT_CLAUDE."
  exit 0
fi

PROMPT="Invoke the domain-architect skill in Mode B (auto-update on drift), following references/auto-update-contract.md EXACTLY.
Changed files in this push:
$CHANGED
Governing docs to refresh (edit ONLY stale sections, grounded in the actual diff; preserve everything still accurate; flag unverifiable changes with an HTML comment instead of inventing):
$DOCS
Read the diff ($BASE..HEAD) for the changed files before editing. Make surgical edits only. If nothing material changed, make no edits."

echo "[domain-architect] rewrite mode — refreshing docs via $CLAUDE_BIN ..."
( cd "$ROOT" && "$CLAUDE_BIN" -p "$PROMPT" --allowedTools "Read,Edit,Bash,Grep,Glob" ) || {
  echo "[domain-architect] rewrite failed — push continues, docs unchanged."; exit 0; }

if ! git -C "$ROOT" diff --quiet -- "$ROOT/docs" $(echo "$DOCS"); then
  git -C "$ROOT" add docs $(echo "$DOCS")
  git -C "$ROOT" commit -m "docs: auto-refresh architecture docs for changed areas

Generated by domain-architect on pre-push. Grounded in the pushed diff;
review with \`git show HEAD\`." >/dev/null
  echo "[domain-architect] doc-refresh commit added: $(git -C "$ROOT" rev-parse --short HEAD)"
  echo "[domain-architect] review with 'git show HEAD', then push again to include it."
  exit 1   # abort this push so the doc commit is part of the next one
fi
echo "[domain-architect] no doc changes needed."
exit 0
